// 13 plans thématiques enrichis (Phase 2)
// Chaque jour : verset principal + méditation + prière + déclaration prophétique
// Format pensé pour /plan-biblique/theme/[id]

export interface ThemedDay {
  day: number;
  reference: string;     // ex "Jean 3:16"
  book: string;
  chapter: number;
  verse: number;
  verseText: string;     // LSG
  meditation: string;    // 2-4 phrases
  prayer: string;        // 1-2 phrases
  declaration: string;   // "Je décrète..." (1 phrase)
}

export interface ThemedPlan {
  id: string;
  title: string;
  description: string;
  emoji: string;
  color: string;         // accent
  totalDays: number;
  days: ThemedDay[];
}

// Helper pour générer rapidement
function d(
  day: number, reference: string, book: string, chapter: number, verse: number,
  verseText: string, meditation: string, prayer: string, declaration: string,
): ThemedDay {
  return { day, reference, book, chapter, verse, verseText, meditation, prayer, declaration };
}

// Note : 7 jours par plan thématique (assez pour engager sans épuiser)
export const THEMED_PLANS: ThemedPlan[] = [
  {
    id: "salut", title: "Le Salut", emoji: "✝️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour comprendre et recevoir le salut offert en Christ.",
    days: [
      d(1, "Jean 3:16", "Jean", 3, 16,
        "Car Dieu a tant aimé le monde qu'il a donné son Fils unique, afin que quiconque croit en lui ne périsse point, mais qu'il ait la vie éternelle.",
        "Le salut commence par l'amour de Dieu. Avant que tu cherches Dieu, Lui te cherchait déjà. La croix n'est pas une transaction froide : c'est un Père qui donne ce qu'il a de plus cher pour ramener son enfant.",
        "Père, merci d'avoir aimé le monde au point de donner Jésus. Je crois en Lui aujourd'hui. Amen.",
        "Je décrète que je suis aimé(e) de Dieu d'un amour éternel."),
      d(2, "Romains 3:23", "Romains", 3, 23,
        "Tous ont péché et sont privés de la gloire de Dieu.",
        "Le salut suppose qu'on reconnaisse notre besoin. Personne ne s'élève au niveau de Dieu par ses propres efforts. Cette honnêteté ouvre la porte à la grâce.",
        "Seigneur, je reconnais que j'ai péché et que j'ai besoin de Toi. Pardonne-moi.",
        "Je décrète que la grâce de Dieu est suffisante pour moi."),
      d(3, "Romains 10:9", "Romains", 10, 9,
        "Si tu confesses de ta bouche le Seigneur Jésus, et si tu crois dans ton cœur que Dieu l'a ressuscité des morts, tu seras sauvé.",
        "Le salut est une affaire de bouche et de cœur. Pas seulement une émotion, pas seulement une idée : une confession publique d'un Seigneur ressuscité.",
        "Jésus, Tu es mon Seigneur. Je crois que Tu es ressuscité. Je T'appartiens.",
        "Je décrète que Jésus est Seigneur sur toute ma vie."),
      d(4, "Éphésiens 2:8", "Éphésiens", 2, 8,
        "Car c'est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c'est le don de Dieu.",
        "Tu n'as rien acheté. Tu as reçu. C'est ce qui rend le salut si scandaleux et si beau : tu ne peux pas le mériter, tu peux juste l'accepter.",
        "Merci Père pour ce cadeau immérité. Je le reçois avec gratitude.",
        "Je décrète que je suis sauvé(e) par grâce, et non par mes œuvres."),
      d(5, "2 Corinthiens 5:17", "2 Corinthiens", 5, 17,
        "Si quelqu'un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées ; voici, toutes choses sont devenues nouvelles.",
        "Le salut n'est pas un rafistolage. Dieu ne répare pas le vieil homme : Il en crée un neuf. Ton passé ne te définit plus.",
        "Père, fais de moi une nouvelle créature aujourd'hui. Je laisse derrière moi tout ce qui n'est pas de Toi.",
        "Je décrète que je suis une nouvelle créature en Christ."),
      d(6, "Jean 10:28", "Jean", 10, 28,
        "Je leur donne la vie éternelle ; et elles ne périront jamais, et personne ne les ravira de ma main.",
        "Le salut est sûr. Une fois dans la main de Jésus, personne ne peut t'en arracher. L'ennemi peut harceler, il ne peut pas voler.",
        "Jésus, je remets ma vie entre Tes mains pour toujours.",
        "Je décrète que je suis en sécurité dans la main du Bon Berger."),
      d(7, "Apocalypse 3:20", "Apocalypse", 3, 20,
        "Voici, je me tiens à la porte, et je frappe. Si quelqu'un entend ma voix et ouvre la porte, j'entrerai chez lui, je souperai avec lui, et lui avec moi.",
        "Le salut n'est pas une formule, c'est une relation. Jésus veut entrer, manger avec toi, partager ta vie au quotidien.",
        "Jésus, j'ouvre grand la porte. Entre, et reste.",
        "Je décrète que Jésus habite ma vie et marche avec moi chaque jour."),
    ],
  },

  {
    id: "foi", title: "La Foi", emoji: "⭐", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour fortifier ta confiance en Dieu, même quand tu ne vois rien.",
    days: [
      d(1, "Hébreux 11:1", "Hébreux", 11, 1,
        "Or la foi est une ferme assurance des choses qu'on espère, une démonstration de celles qu'on ne voit pas.",
        "La foi n'est pas un saut dans le vide. C'est une assurance fondée sur le caractère de Dieu. Tu peux croire l'invisible parce que Celui qui l'a promis est fidèle.",
        "Père, augmente ma foi. Apprends-moi à voir avec Tes yeux.",
        "Je décrète que je marche par la foi, et non par la vue."),
      d(2, "Romains 10:17", "Romains", 10, 17,
        "Ainsi la foi vient de ce qu'on entend, et ce qu'on entend vient de la parole de Christ.",
        "La foi pousse là où la Parole est plantée. Si ta foi est faible, ce n'est pas un défaut de personnalité : c'est une question de nourriture.",
        "Seigneur, ouvre mes oreilles à Ta Parole. Que je l'entende et qu'elle me transforme.",
        "Je décrète que ma foi grandit chaque fois que j'écoute la Parole."),
      d(3, "Marc 11:24", "Marc", 11, 24,
        "Tout ce que vous demanderez en priant, croyez que vous l'avez reçu, et vous le verrez s'accomplir.",
        "Jésus inverse l'ordre : on croit avant de voir. Le « reçu » précède le « visible ». C'est l'inverse du monde, c'est le chemin du Royaume.",
        "Père, j'ai déjà reçu ce que je Te demande. Merci d'avance.",
        "Je décrète que ce que j'ai demandé selon Ta volonté est déjà à moi."),
      d(4, "Jacques 1:6", "Jacques", 1, 6,
        "Mais qu'il la demande avec foi, sans douter ; car celui qui doute est semblable au flot de la mer, agité par le vent et poussé de côté et d'autre.",
        "Le doute n'est pas une opinion neutre : c'est un vent qui ballotte. Choisis ta direction et tiens bon.",
        "Seigneur, stabilise mon cœur. Que je ne sois plus ballotté par le doute.",
        "Je décrète que mon cœur est ancré dans la fidélité de Dieu."),
      d(5, "Matthieu 17:20", "Matthieu", 17, 20,
        "Si vous aviez de la foi comme un grain de sénevé, vous diriez à cette montagne : Transporte-toi d'ici là, et elle se transporterait.",
        "Jésus ne demande pas une grande foi, mais une foi vivante. Le grain de sénevé est minuscule mais vivant — et il pousse.",
        "Jésus, je T'apporte ma petite foi. Fais-la grandir.",
        "Je décrète que ma foi déplace les montagnes que la vie pose devant moi."),
      d(6, "2 Corinthiens 5:7", "2 Corinthiens", 5, 7,
        "Car nous marchons par la foi et non par la vue.",
        "Marcher par la foi, c'est avancer même quand la vue dit « non ». Les yeux décrivent le présent, la foi décrit la promesse.",
        "Père, je choisis de Te faire confiance même quand je ne comprends pas.",
        "Je décrète que je marche par la foi à chaque pas."),
      d(7, "Hébreux 11:6", "Hébreux", 11, 6,
        "Or sans la foi il est impossible de lui être agréable ; car il faut que celui qui s'approche de Dieu croie que Dieu existe, et qu'il est le rémunérateur de ceux qui le cherchent.",
        "Dieu ne se contente pas de notre présence : Il veut notre confiance. Le chercher, c'est croire qu'Il répond.",
        "Père, je Te cherche aujourd'hui de tout mon cœur. Je crois que Tu me récompenseras.",
        "Je décrète que Dieu récompense ma quête sincère."),
    ],
  },

  {
    id: "priere", title: "La Prière", emoji: "🕯️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour développer une vie de prière intime et puissante.",
    days: [
      d(1, "Matthieu 6:6", "Matthieu", 6, 6,
        "Mais quand tu pries, entre dans ta chambre, ferme ta porte, et prie ton Père qui est là dans le lieu secret ; et ton Père, qui voit dans le secret, te le rendra.",
        "La prière la plus puissante est cachée. Pas de public, pas de performance. Juste toi et Lui dans le secret.",
        "Père, fais de moi un homme/une femme du lieu secret.",
        "Je décrète que ma vie cachée avec Dieu produit des fruits visibles."),
      d(2, "1 Thessaloniciens 5:17", "1 Thessaloniciens", 5, 17,
        "Priez sans cesse.",
        "Prier sans cesse, ce n'est pas marmonner toute la journée. C'est garder la ligne ouverte avec le Père, comme on respire.",
        "Esprit Saint, apprends-moi à T'inclure dans chaque instant.",
        "Je décrète que je marche dans une conversation continue avec Dieu."),
      d(3, "Philippiens 4:6", "Philippiens", 4, 6,
        "Ne vous inquiétez de rien ; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces.",
        "L'inquiétude et la prière ne peuvent pas coexister longtemps. Choisis laquelle tu nourris.",
        "Père, je dépose mes inquiétudes à Tes pieds. Merci de prendre soin de tout.",
        "Je décrète que je suis libre de l'inquiétude par la prière."),
      d(4, "Jacques 5:16", "Jacques", 5, 16,
        "La prière fervente du juste a une grande efficace.",
        "Pas la prière polie. La prière fervente. Celle qui jaillit du cœur, qui ne lâche pas, qui croit.",
        "Seigneur, allume en moi un feu de prière fervente.",
        "Je décrète que ma prière est puissante parce que je suis juste en Christ."),
      d(5, "Matthieu 7:7", "Matthieu", 7, 7,
        "Demandez, et l'on vous donnera ; cherchez, et vous trouverez ; frappez, et l'on vous ouvrira.",
        "Jésus emploie trois verbes croissants : demande, cherche, frappe. La prière persévérante n'est pas du harcèlement, c'est de l'amour qui ne lâche pas.",
        "Père, je continue à demander, à chercher, à frapper. Tu réponds en Ton temps.",
        "Je décrète que les portes que je frappe avec foi s'ouvrent devant moi."),
      d(6, "Jean 15:7", "Jean", 15, 7,
        "Si vous demeurez en moi, et que mes paroles demeurent en vous, demandez ce que vous voudrez, et cela vous sera accordé.",
        "La prière exaucée est ancrée dans l'intimité. « Demeurer » d'abord, « demander » ensuite.",
        "Jésus, je demeure en Toi aujourd'hui. Ta Parole demeure en moi.",
        "Je décrète que je demeure en Christ et qu'Il demeure en moi."),
      d(7, "Romains 8:26", "Romains", 8, 26,
        "L'Esprit lui-même intercède par des soupirs inexprimables.",
        "Quand les mots manquent, l'Esprit prend le relais. Tu n'es jamais seul dans ta prière, même quand tu ne sais que dire.",
        "Esprit Saint, prie en moi, prie pour moi, prie à travers moi.",
        "Je décrète que l'Esprit Saint intercède pour moi sans relâche."),
    ],
  },

  {
    id: "amour", title: "L'Amour", emoji: "❤️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour recevoir et refléter l'amour de Dieu.",
    days: [
      d(1, "1 Jean 4:8", "1 Jean", 4, 8,
        "Celui qui n'aime pas n'a pas connu Dieu, car Dieu est amour.",
        "Dieu n'a pas seulement de l'amour : Il EST amour. C'est Sa nature. Connaître Dieu, c'est apprendre à aimer.",
        "Père, fais de moi un témoin vivant de Ton amour.",
        "Je décrète que l'amour de Dieu coule à travers moi."),
      d(2, "Jean 13:34", "Jean", 13, 34,
        "Je vous donne un commandement nouveau : Aimez-vous les uns les autres ; comme je vous ai aimés, vous aussi, aimez-vous les uns les autres.",
        "Le standard n'est plus « aime ton prochain comme toi-même ». Jésus relève la barre : « comme JE vous ai aimés ». C'est-à-dire jusqu'à la croix.",
        "Jésus, donne-moi de Ton amour pour ceux qui m'entourent.",
        "Je décrète que j'aime comme Jésus aime."),
      d(3, "1 Corinthiens 13:4", "1 Corinthiens", 13, 4,
        "L'amour est patient, il est plein de bonté ; l'amour n'est point envieux ; l'amour ne se vante point, il ne s'enfle point d'orgueil.",
        "L'amour biblique n'est pas un sentiment, c'est un comportement. Remplace « amour » par ton prénom : est-ce que ça décrit ta semaine ?",
        "Père, transforme mon caractère pour qu'il ressemble à ton amour.",
        "Je décrète que je manifeste un amour patient et bienveillant."),
      d(4, "Romains 5:8", "Romains", 5, 8,
        "Mais Dieu prouve son amour envers nous, en ce que, lorsque nous étions encore des pécheurs, Christ est mort pour nous.",
        "Dieu ne t'a pas attendu pour devenir aimable. Il t'a aimé dans ton pire jour. C'est ça la nouvelle scandaleuse de l'Évangile.",
        "Merci Père de m'avoir aimé alors que je ne le méritais pas.",
        "Je décrète que je suis aimé(e) sans condition par Dieu."),
      d(5, "Sophonie 3:17", "Sophonie", 3, 17,
        "L'Éternel, ton Dieu, est au milieu de toi, comme un héros qui sauve ; il fera de toi sa plus grande joie.",
        "Dieu chante de joie sur toi. Tu n'es pas un projet à corriger. Tu es Sa joie.",
        "Père, je reçois Ta joie sur moi aujourd'hui.",
        "Je décrète que je suis la joie de mon Père."),
      d(6, "Jean 15:13", "Jean", 15, 13,
        "Il n'y a pas de plus grand amour que de donner sa vie pour ses amis.",
        "Aimer, c'est dépenser sa vie pour les autres. Pas seulement mourir, mais vivre POUR. Ton emploi du temps trahit qui tu aimes.",
        "Jésus, apprends-moi à donner ma vie pour ceux que Tu me confies.",
        "Je décrète que je vis pour ceux que Dieu place sur ma route."),
      d(7, "1 Jean 4:18", "1 Jean", 4, 18,
        "La crainte n'est pas dans l'amour, mais l'amour parfait bannit la crainte.",
        "Tu ne peux pas marcher dans l'amour et la peur en même temps. L'amour parfait de Dieu chasse la peur du jugement.",
        "Père, immerge-moi dans Ton amour parfait. Que la peur s'en aille.",
        "Je décrète que l'amour parfait de Dieu chasse toute crainte de moi."),
    ],
  },

  {
    id: "pardon", title: "Le Pardon", emoji: "🕊️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour recevoir le pardon de Dieu et libérer ceux qui t'ont blessé.",
    days: [
      d(1, "1 Jean 1:9", "1 Jean", 1, 9,
        "Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner, et pour nous purifier de toute iniquité.",
        "Confesser n'est pas s'humilier devant un juge sévère, c'est s'ouvrir devant un Père fidèle. Sa fidélité est garantie.",
        "Père, je confesse mes péchés. Purifie-moi maintenant.",
        "Je décrète que je suis purifié(e) par le sang de Jésus."),
      d(2, "Matthieu 6:14", "Matthieu", 6, 14,
        "Si vous pardonnez aux hommes leurs offenses, votre Père céleste vous pardonnera aussi.",
        "Le pardon est circulaire. Refuser de pardonner, c'est barrer le canal par lequel nous recevons. Pardonner libère deux personnes : l'autre et toi.",
        "Père, donne-moi la grâce de pardonner comme Tu m'as pardonné.",
        "Je décrète que je libère ceux qui m'ont blessé(e)."),
      d(3, "Colossiens 3:13", "Colossiens", 3, 13,
        "Si l'un a sujet de se plaindre de l'autre, pardonnez-vous réciproquement. De même que Christ vous a pardonné, pardonnez-vous aussi.",
        "Le standard du pardon n'est pas la mesure de l'offense, mais la mesure de la grâce reçue. Christ t'a tout pardonné.",
        "Jésus, je pardonne comme Tu m'as pardonné. Aide-moi.",
        "Je décrète que je pardonne sans mesure parce que je suis pardonné(e) sans mesure."),
      d(4, "Éphésiens 4:32", "Éphésiens", 4, 32,
        "Soyez bons les uns envers les autres, compatissants, vous pardonnant réciproquement, comme Dieu vous a pardonné en Christ.",
        "La bonté précède le pardon. Décide d'être bon, et le pardon suivra. C'est un choix, pas une humeur.",
        "Père, fais de moi un instrument de bonté et de pardon.",
        "Je décrète que je marche dans la bonté et la compassion."),
      d(5, "Michée 7:19", "Michée", 7, 19,
        "Tu jetteras au fond de la mer tous leurs péchés.",
        "Dieu ne classe pas tes péchés pardonnés dans un dossier consultable. Il les jette au fond de la mer. Pourquoi pêcher ce qu'Il a noyé ?",
        "Merci Père, mon passé est noyé sous Ton pardon.",
        "Je décrète que mon passé n'a plus de pouvoir sur moi."),
      d(6, "Luc 23:34", "Luc", 23, 34,
        "Père, pardonne-leur, car ils ne savent ce qu'ils font.",
        "Sur la croix, Jésus pardonne avant qu'on lui demande pardon. Le pardon précède même la repentance. C'est la grâce qui ouvre le chemin.",
        "Jésus, par Ton Esprit, je pardonne ceux qui ne savent pas le mal qu'ils m'ont fait.",
        "Je décrète que je libère ceux qui n'ont pas conscience de m'avoir blessé(e)."),
      d(7, "Psaumes 103:12", "Psaumes", 103, 12,
        "Autant l'orient est éloigné de l'occident, autant il éloigne de nous nos transgressions.",
        "La distance est infinie. Dieu n'a pas mis tes péchés « du nord au sud » (limité par les pôles), mais « est-ouest » (infini). Pour toujours.",
        "Père, je reçois la distance infinie entre moi et mes péchés.",
        "Je décrète que mes péchés sont éloignés de moi pour toujours."),
    ],
  },

  {
    id: "saint-esprit", title: "Le Saint-Esprit", emoji: "🕊️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour grandir dans l'intimité avec le Saint-Esprit.",
    days: [
      d(1, "Jean 14:16", "Jean", 14, 16,
        "Et moi, je prierai le Père, et il vous donnera un autre consolateur, afin qu'il demeure éternellement avec vous.",
        "Le Saint-Esprit n'est pas un courant d'énergie. C'est une Personne, le Consolateur, donné pour rester avec toi pour toujours.",
        "Saint-Esprit, merci d'être avec moi pour toujours. Sois mon Consolateur.",
        "Je décrète que le Saint-Esprit habite en moi pour l'éternité."),
      d(2, "Actes 1:8", "Actes", 1, 8,
        "Vous recevrez une puissance, le Saint-Esprit survenant sur vous.",
        "L'Esprit te donne une puissance — pas une décoration, mais une force pour vivre et témoigner.",
        "Esprit Saint, je T'invite à me revêtir de Ta puissance.",
        "Je décrète que je suis rempli(e) de la puissance d'en haut."),
      d(3, "Galates 5:22", "Galates", 5, 22,
        "Mais le fruit de l'Esprit, c'est l'amour, la joie, la paix, la patience, la bonté, la bénignité, la fidélité.",
        "Tu ne produis pas le fruit, tu le portes. C'est le rôle de l'Esprit. Ton job : rester branché.",
        "Esprit Saint, fais croître Ton fruit dans ma vie.",
        "Je décrète que je porte le fruit de l'Esprit en abondance."),
      d(4, "Romains 8:14", "Romains", 8, 14,
        "Tous ceux qui sont conduits par l'Esprit de Dieu sont fils de Dieu.",
        "Être conduit par l'Esprit, c'est apprendre à reconnaître Sa voix dans le petit murmure du cœur. Cela se cultive.",
        "Père, apprends-moi à entendre la voix de Ton Esprit chaque jour.",
        "Je décrète que je suis conduit(e) par l'Esprit de Dieu."),
      d(5, "1 Corinthiens 6:19", "1 Corinthiens", 6, 19,
        "Votre corps est le temple du Saint-Esprit qui est en vous, que vous avez reçu de Dieu.",
        "Tu es littéralement la maison de Dieu. Comment tu traites ton corps, ton temps, ton esprit, ça concerne le Locataire divin.",
        "Esprit Saint, prends possession de chaque pièce de mon être.",
        "Je décrète que mon corps est le temple sacré du Saint-Esprit."),
      d(6, "Jean 16:13", "Jean", 16, 13,
        "Quand le consolateur sera venu, l'Esprit de vérité, il vous conduira dans toute la vérité.",
        "L'Esprit est le guide vers la vérité. Quand tu lis la Parole, demande-Lui de t'éclairer : ce n'est pas une option, c'est un appel à Lui ouvrir le texte.",
        "Esprit de vérité, ouvre-moi les Écritures aujourd'hui.",
        "Je décrète que je marche dans la vérité que l'Esprit me révèle."),
      d(7, "Éphésiens 5:18", "Éphésiens", 5, 18,
        "Soyez remplis de l'Esprit.",
        "L'ordre est continu : « soyez en train d'être remplis ». La plénitude n'est pas un événement unique, c'est un rythme quotidien.",
        "Esprit Saint, remplis-moi à nouveau aujourd'hui.",
        "Je décrète que je suis rempli(e) de l'Esprit jour après jour."),
    ],
  },

  {
    id: "jeune", title: "Le Jeûne", emoji: "🍃", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour comprendre la puissance spirituelle du jeûne.",
    days: [
      d(1, "Matthieu 6:16", "Matthieu", 6, 16,
        "Lorsque vous jeûnez, ne prenez pas un air triste, comme les hypocrites.",
        "Jésus dit « lorsque », pas « si ». Le jeûne est attendu dans la vie du disciple. Mais discret, joyeux, secret.",
        "Père, apprends-moi à jeûner pour Toi, pas pour les hommes.",
        "Je décrète que mon jeûne est un parfum agréable à Dieu."),
      d(2, "Ésaïe 58:6", "Ésaïe", 58, 6,
        "Voici le jeûne auquel je prends plaisir : Détache les chaînes de la méchanceté, dénoue les liens de la servitude.",
        "Le vrai jeûne brise des chaînes. C'est une arme spirituelle, pas un régime religieux.",
        "Seigneur, que mon jeûne brise les chaînes autour de moi et autour des miens.",
        "Je décrète que les chaînes se brisent par la puissance du jeûne."),
      d(3, "Matthieu 17:21", "Matthieu", 17, 21,
        "Cette sorte de démon ne sort que par la prière et par le jeûne.",
        "Il y a des combats qu'on ne gagne qu'à genoux et le ventre vide. Pas une question de mérite, mais d'accès spirituel.",
        "Père, je m'humilie devant Toi par le jeûne. Combats pour moi.",
        "Je décrète que les forteresses tombent par la prière et le jeûne."),
      d(4, "Joël 2:12", "Joël", 2, 12,
        "Maintenant encore, dit l'Éternel, revenez à moi de tout votre cœur, avec des jeûnes, avec des pleurs et des lamentations.",
        "Le jeûne est un retour. Une manière physique de dire : « Tu comptes plus que la nourriture, plus que le confort. »",
        "Père, je reviens à Toi de tout mon cœur.",
        "Je décrète que mon cœur revient pleinement à Dieu."),
      d(5, "Daniel 10:3", "Daniel", 10, 3,
        "Je ne mangeai aucun mets délicat, il n'entra ni viande ni vin dans ma bouche.",
        "Daniel jeûne 21 jours et déclenche une guerre angélique. Ton jeûne déplace des choses que tu ne vois pas.",
        "Père, que mon jeûne mobilise les armées du ciel pour mes batailles.",
        "Je décrète qu'une percée spirituelle est en train de se produire."),
      d(6, "Esdras 8:23", "Esdras", 8, 23,
        "C'est à cause de cela que nous jeûnâmes et que nous invoquâmes notre Dieu. Et il nous exauça.",
        "Le jeûne accompagné de prière reçoit une réponse. Ce n'est pas mécanique, c'est relationnel — mais c'est puissant.",
        "Seigneur, exauce-moi comme Tu as exaucé Esdras.",
        "Je décrète que Dieu exauce la prière de mon jeûne."),
      d(7, "Actes 13:2", "Actes", 13, 2,
        "Pendant qu'ils servaient le Seigneur dans leur ministère et qu'ils jeûnaient, le Saint-Esprit dit : Mettez-moi à part Barnabas et Saul.",
        "C'est dans le jeûne que la direction divine devient claire. Quand tu fais taire la chair, l'Esprit parle plus distinctement.",
        "Saint-Esprit, parle-moi clairement dans ce jeûne. Mets-moi à part pour Ton œuvre.",
        "Je décrète que la direction divine devient claire pour ma vie."),
    ],
  },

  {
    id: "discipline", title: "La Discipline", emoji: "🎯", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour bâtir une vie chrétienne disciplinée et fructueuse.",
    days: [
      d(1, "1 Corinthiens 9:27", "1 Corinthiens", 9, 27,
        "Je traite durement mon corps et je le tiens assujetti.",
        "Paul parle comme un athlète. La vie chrétienne n'est pas du laxisme spirituel : c'est de l'entraînement quotidien.",
        "Père, apprends-moi à discipliner mon corps pour Ta gloire.",
        "Je décrète que je maîtrise mon corps et qu'il sert Dieu."),
      d(2, "Hébreux 12:11", "Hébreux", 12, 11,
        "Il est vrai que toute correction semble d'abord un sujet de tristesse, et non de joie ; mais elle produit plus tard pour ceux qui ont été ainsi exercés un fruit paisible de justice.",
        "La discipline pique sur le moment et libère sur la durée. Ne fuis pas la formation : c'est ton avenir qui se construit.",
        "Père, donne-moi la patience d'accepter Ta formation.",
        "Je décrète que la discipline d'aujourd'hui me prépare la liberté de demain."),
      d(3, "2 Timothée 1:7", "2 Timothée", 1, 7,
        "Dieu nous a donné un esprit de force, d'amour et de sagesse.",
        "Le mot grec pour « sagesse » ici signifie aussi « maîtrise de soi ». Cette capacité est un don de Dieu, pas une performance perso.",
        "Saint-Esprit, donne-moi la maîtrise de moi-même.",
        "Je décrète que je suis maître de mes émotions et de mes désirs."),
      d(4, "Proverbes 25:28", "Proverbes", 25, 28,
        "Comme une ville forcée et sans murailles, ainsi est l'homme qui n'est pas maître de lui-même.",
        "Sans maîtrise de soi, tu es une ville ouverte aux ennemis. Construis les murs un brique à la fois.",
        "Seigneur, bâtis en moi les remparts de la maîtrise.",
        "Je décrète que mes murailles intérieures sont solides."),
      d(5, "Galates 5:23", "Galates", 5, 23,
        "Le fruit de l'Esprit est… la tempérance.",
        "La maîtrise de soi est un fruit. Tu ne la fabriques pas par volonté pure ; tu la cultives en demeurant en Christ.",
        "Esprit Saint, fais croître en moi la tempérance.",
        "Je décrète que je porte le fruit de la maîtrise de moi-même."),
      d(6, "Luc 9:23", "Luc", 9, 23,
        "Si quelqu'un veut venir après moi, qu'il renonce à lui-même, qu'il se charge chaque jour de sa croix, et qu'il me suive.",
        "« Chaque jour ». La discipline chrétienne est un quotidien. Pas un événement annuel.",
        "Jésus, je me charge de ma croix aujourd'hui. Conduis-moi.",
        "Je décrète que je suis Jésus chaque jour."),
      d(7, "Philippiens 4:13", "Philippiens", 4, 13,
        "Je puis tout par celui qui me fortifie.",
        "La discipline n'est pas une question de volonté pure. C'est une dépendance active à la puissance du Christ qui te fortifie.",
        "Christ, fortifie-moi pour vivre ce que Tu m'appelles à vivre.",
        "Je décrète que je peux tout par Christ qui me fortifie."),
    ],
  },

  {
    id: "guerison", title: "La Guérison", emoji: "🩹", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour t'approprier la guérison promise en Christ.",
    days: [
      d(1, "Ésaïe 53:5", "Ésaïe", 53, 5,
        "C'est par ses meurtrissures que nous sommes guéris.",
        "La guérison est dans la croix. Ce n'est pas une faveur à mendier : c'est une provision déjà payée.",
        "Jésus, je reçois la guérison Tu as acquise pour moi par Tes meurtrissures.",
        "Je décrète que je suis guéri(e) par les meurtrissures de Jésus."),
      d(2, "Exode 15:26", "Exode", 15, 26,
        "Je suis l'Éternel, qui te guérit.",
        "Dieu se révèle comme « celui qui guérit » — Jéhovah Rapha. C'est un nom, donc un caractère permanent.",
        "Jéhovah Rapha, mon Guérisseur, je T'adore.",
        "Je décrète que mon Dieu est mon Guérisseur."),
      d(3, "Jacques 5:14", "Jacques", 5, 14,
        "Quelqu'un parmi vous est-il malade ? Qu'il appelle les anciens de l'Église, et que les anciens prient pour lui.",
        "La guérison passe souvent par la communauté. N'isole pas ta maladie : appelle les anciens, demande la prière.",
        "Seigneur, donne-moi le courage d'appeler à l'aide. Envoie-moi des intercesseurs.",
        "Je décrète que je reçois la prière de la foi pour ma guérison."),
      d(4, "Marc 5:34", "Marc", 5, 34,
        "Ma fille, ta foi t'a sauvée ; va en paix, et sois guérie de ton mal.",
        "La femme malade depuis 12 ans active la guérison par la foi. Le Christ ne ment pas : Il guérit toujours quand on touche le bord de Son vêtement.",
        "Jésus, je touche le bord de Ton vêtement aujourd'hui par la foi.",
        "Je décrète que ma foi active la guérison de Jésus."),
      d(5, "Psaumes 103:3", "Psaumes", 103, 3,
        "C'est lui qui pardonne toutes tes iniquités, qui guérit toutes tes maladies.",
        "Pardon et guérison sont jumelés dans la même phrase. Dieu ne fait pas de distinction : c'est la même œuvre rédemptrice.",
        "Père, pardonne-moi et guéris-moi.",
        "Je décrète que je suis pardonné(e) et guéri(e) totalement."),
      d(6, "Jérémie 17:14", "Jérémie", 17, 14,
        "Guéris-moi, Éternel, et je serai guéri ; sauve-moi, et je serai sauvé.",
        "Jérémie prie avec assurance : « Si Tu guéris, je SERAI guéri. » Ta prière a-t-elle cette confiance ?",
        "Éternel, guéris-moi. Je sais que je serai guéri(e).",
        "Je décrète que la guérison de Dieu est complète sur moi."),
      d(7, "3 Jean 1:2", "3 Jean", 1, 2,
        "Je souhaite que tu prospères à tous égards et sois en bonne santé.",
        "Le souhait de Dieu pour toi est la santé intégrale. Reçois-le comme Sa volonté pour aujourd'hui.",
        "Père, je reçois Ton souhait de santé pour moi.",
        "Je décrète que je prospère et suis en bonne santé."),
    ],
  },

  {
    id: "sanctification", title: "La Sanctification", emoji: "✨", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour grandir dans la sainteté pratique au quotidien.",
    days: [
      d(1, "1 Thessaloniciens 4:3", "1 Thessaloniciens", 4, 3,
        "Ce que Dieu veut, c'est votre sanctification.",
        "La volonté de Dieu pour toi est claire : ta sanctification. Pas Sa popularité, pas ton confort. Ta transformation.",
        "Père, sanctifie-moi entièrement.",
        "Je décrète que je suis mis(e) à part pour Dieu."),
      d(2, "Romains 12:2", "Romains", 12, 2,
        "Ne vous conformez pas au siècle présent, mais soyez transformés par le renouvellement de l'intelligence.",
        "La sanctification passe par le mental. Ce que tu nourris (vidéos, conversations, livres) sculpte ton intelligence.",
        "Esprit Saint, renouvelle mon intelligence aujourd'hui.",
        "Je décrète que ma pensée est renouvelée chaque jour."),
      d(3, "1 Pierre 1:16", "1 Pierre", 1, 16,
        "Vous serez saints, car je suis saint.",
        "La sainteté n'est pas une moralité légaliste : c'est une ressemblance familiale. Tu es appelé à refléter Ton Père.",
        "Père, fais de moi un reflet de Ta sainteté.",
        "Je décrète que je porte la sainteté de mon Père."),
      d(4, "Hébreux 12:14", "Hébreux", 12, 14,
        "Recherchez la sanctification, sans laquelle personne ne verra le Seigneur.",
        "La sanctification se RECHERCHE. C'est actif. Tu ne deviens pas saint en flottant ; tu poursuis intentionnellement.",
        "Seigneur, je veux Te voir. Donne-moi la faim de la sainteté.",
        "Je décrète que je poursuis activement la sanctification."),
      d(5, "Jean 17:17", "Jean", 17, 17,
        "Sanctifie-les par ta vérité : ta parole est la vérité.",
        "La Parole sanctifie. Sans Bible ouverte, pas de sanctification profonde. C'est l'eau qui te lave de l'intérieur.",
        "Père, sanctifie-moi par Ta Parole aujourd'hui.",
        "Je décrète que la Parole de Dieu me purifie et me transforme."),
      d(6, "2 Corinthiens 7:1", "2 Corinthiens", 7, 1,
        "Purifions-nous de toute souillure de la chair et de l'esprit.",
        "La sanctification est double : du corps et de l'esprit. Pas juste ne plus pécher en actes, mais aussi en pensées.",
        "Seigneur, purifie-moi extérieurement et intérieurement.",
        "Je décrète que je suis purifié(e) corps et esprit."),
      d(7, "Philippiens 1:6", "Philippiens", 1, 6,
        "Celui qui a commencé en vous cette bonne œuvre la rendra parfaite pour le jour de Jésus-Christ.",
        "La sanctification est un processus, pas un événement. Dieu finira ce qu'Il a commencé. Patience avec toi-même.",
        "Père, achève en moi l'œuvre que Tu as commencée.",
        "Je décrète que Dieu accomplit en moi Son œuvre parfaite."),
    ],
  },

  {
    id: "leadership", title: "Le Leadership", emoji: "👑", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour devenir un leader serviteur selon le cœur de Dieu.",
    days: [
      d(1, "Marc 10:43", "Marc", 10, 43,
        "Quiconque veut être grand parmi vous, qu'il soit votre serviteur.",
        "Le leadership chrétien inverse la pyramide. Plus tu montes, plus tu sers. Le sommet, c'est la position du tablier.",
        "Jésus, fais de moi un leader qui sert.",
        "Je décrète que je grandis en servant les autres."),
      d(2, "Proverbes 11:14", "Proverbes", 11, 14,
        "Quand la prudence fait défaut, le peuple tombe ; et le salut est dans le grand nombre des conseillers.",
        "Le leader ne décide pas seul. Entoure-toi de conseillers sages : c'est de la prudence, pas de la faiblesse.",
        "Père, donne-moi des conseillers sages et un cœur enseignable.",
        "Je décrète que je m'entoure de sagesse multiple."),
      d(3, "Néhémie 4:14", "Néhémie", 4, 14,
        "N'ayez pas peur d'eux ! Souvenez-vous du Seigneur, grand et redoutable, et combattez.",
        "Le leader rappelle aux siens qui est leur Dieu. Quand la peur monte, ton job est de pointer vers le Seigneur.",
        "Seigneur, donne-moi le courage de leader sans craindre les hommes.",
        "Je décrète que je rappelle aux miens la grandeur de Dieu."),
      d(4, "1 Timothée 4:12", "1 Timothée", 4, 12,
        "Sois un modèle pour les fidèles, en parole, en conduite, en charité, en foi, en pureté.",
        "Le leadership se voit. Cinq domaines à incarner : parole, conduite, amour, foi, pureté. Pas un, les cinq.",
        "Père, fais de moi un modèle dans tous les domaines.",
        "Je décrète que ma vie est un témoignage cohérent."),
      d(5, "Jean 13:14", "Jean", 13, 14,
        "Si donc je vous ai lavé les pieds, moi, le Seigneur et le Maître, vous devez aussi vous laver les pieds les uns aux autres.",
        "Jésus, le Maître, lave les pieds. Si Lui le fait, aucune tâche n'est au-dessous d'un leader chrétien.",
        "Jésus, donne-moi un cœur de serviteur comme le Tien.",
        "Je décrète que je sers avec humilité et amour."),
      d(6, "Exode 18:21", "Exode", 18, 21,
        "Choisis parmi tout le peuple des hommes capables, craignant Dieu… établis-les sur eux comme chefs.",
        "Le leader délègue. Refuser de partager le fardeau, c'est étouffer le peuple et toi-même.",
        "Père, donne-moi le discernement pour déléguer aux bonnes personnes.",
        "Je décrète que je raise up d'autres leaders autour de moi."),
      d(7, "Hébreux 13:17", "Hébreux", 13, 17,
        "Veillez sur vos âmes, comme devant en rendre compte.",
        "Le leader rend des comptes. Devant Dieu. Pour les âmes confiées. C'est une responsabilité sacrée, pas un titre.",
        "Seigneur, rends-moi conscient de la valeur des âmes que Tu me confies.",
        "Je décrète que je veille avec soin sur ceux que Dieu m'a confiés."),
    ],
  },

  {
    id: "combat-spirituel", title: "Le Combat Spirituel", emoji: "⚔️", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour t'équiper et gagner les batailles invisibles.",
    days: [
      d(1, "Éphésiens 6:12", "Éphésiens", 6, 12,
        "Nous avons à lutter, non contre la chair et le sang, mais contre les principautés, contre les puissances.",
        "Ton vrai ennemi n'est pas la personne qui t'a blessé. Identifie le bon adversaire avant de tirer dans la mauvaise direction.",
        "Père, ouvre mes yeux sur le vrai combat.",
        "Je décrète que je combats dans la dimension spirituelle, pas charnelle."),
      d(2, "Éphésiens 6:11", "Éphésiens", 6, 11,
        "Revêtez-vous de toutes les armes de Dieu, afin de pouvoir tenir ferme.",
        "Dieu a déjà fourni l'armure complète. Ton job : la revêtir. Chaque matin, équipe-toi mentalement.",
        "Père, je revêts aujourd'hui toutes Tes armes.",
        "Je décrète que je suis revêtu(e) de l'armure de Dieu."),
      d(3, "2 Corinthiens 10:4", "2 Corinthiens", 10, 4,
        "Les armes avec lesquelles nous combattons ne sont pas charnelles ; mais elles sont puissantes, par la vertu de Dieu, pour renverser des forteresses.",
        "Tes armes ne sont pas humaines. Elles ont la puissance divine pour démolir ce qui résiste depuis des générations.",
        "Seigneur, mes armes sont puissantes en Toi. Démolis les forteresses.",
        "Je décrète que les forteresses tombent par la puissance de Dieu."),
      d(4, "Jacques 4:7", "Jacques", 4, 7,
        "Soumettez-vous donc à Dieu ; résistez au diable, et il fuira loin de vous.",
        "L'ordre compte. D'abord soumission à Dieu, ensuite résistance au diable. Sans la première, la seconde est inefficace.",
        "Père, je me soumets à Toi. Diable, je te résiste au nom de Jésus.",
        "Je décrète que le diable fuit loin de moi parce que je résiste."),
      d(5, "Apocalypse 12:11", "Apocalypse", 12, 11,
        "Ils l'ont vaincu à cause du sang de l'Agneau et à cause de la parole de leur témoignage.",
        "Deux armes décisives : le sang de Jésus (la rédemption) et le témoignage (ta voix). Combine les deux.",
        "Jésus, je revendique Ton sang sur ma vie. Je proclame ce que Tu as fait pour moi.",
        "Je décrète victoire par le sang de l'Agneau et par ma parole."),
      d(6, "Luc 10:19", "Luc", 10, 19,
        "Voici, je vous ai donné le pouvoir de marcher sur les serpents et les scorpions, et sur toute la puissance de l'ennemi.",
        "L'autorité est donnée, pas à conquérir. Marche dans ce qui t'appartient déjà en Christ.",
        "Jésus, je marche dans l'autorité que Tu m'as donnée.",
        "Je décrète que toute puissance de l'ennemi est sous mes pieds."),
      d(7, "Romains 8:37", "Romains", 8, 37,
        "Nous sommes plus que vainqueurs par celui qui nous a aimés.",
        "Pas seulement vainqueurs. PLUS que vainqueurs. La victoire est si complète qu'il faut un nouveau mot.",
        "Christ, en Toi je suis plus que vainqueur. Merci.",
        "Je décrète que je suis plus que vainqueur(e) par Christ."),
    ],
  },

  {
    id: "grace", title: "La Grâce", emoji: "🌟", color: "#5B21B6", totalDays: 7,
    description: "7 jours pour t'immerger dans la grâce qui te rend libre.",
    days: [
      d(1, "Éphésiens 2:8", "Éphésiens", 2, 8,
        "Car c'est par la grâce que vous êtes sauvés, par le moyen de la foi.",
        "La grâce, c'est la faveur imméritée. Tu ne paies rien, tu reçois tout. Cesse d'essayer de mériter ce qui t'est offert.",
        "Père, je reçois Ta grâce aujourd'hui sans la mériter.",
        "Je décrète que je suis sauvé(e) par grâce et non par mes œuvres."),
      d(2, "2 Corinthiens 12:9", "2 Corinthiens", 12, 9,
        "Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse.",
        "Ta faiblesse n'est pas un obstacle à la grâce, c'est son terrain de jeu. Cesse de cacher ce qui est faible en toi.",
        "Père, dans ma faiblesse, que Ta grâce soit suffisante.",
        "Je décrète que la grâce de Dieu me suffit en tout temps."),
      d(3, "Tite 2:11", "Tite", 2, 11,
        "Car la grâce de Dieu, source de salut pour tous les hommes, a été manifestée.",
        "La grâce de Dieu est universelle dans son offre. Aucun visage n'est exclu. Personne n'est trop loin.",
        "Père, merci pour Ta grâce qui ne fait aucune exception.",
        "Je décrète que la grâce de Dieu rejoint tous ceux que j'aime."),
      d(4, "Romains 5:20", "Romains", 5, 20,
        "Là où le péché a abondé, la grâce a surabondé.",
        "Là où tu pensais être trop loin, la grâce arrive en surplus. Ton péché ne dépasse jamais Sa grâce.",
        "Père, là où le péché a abondé en moi, fais surabonder Ta grâce.",
        "Je décrète que la grâce surabonde dans ma vie."),
      d(5, "Hébreux 4:16", "Hébreux", 4, 16,
        "Approchons-nous donc avec assurance du trône de la grâce.",
        "Le trône de Dieu est appelé « trône de la grâce ». Tu n'y vas pas en accusé ; tu y vas en enfant. Avec assurance.",
        "Père, je m'approche de Toi avec assurance.",
        "Je décrète que j'accède librement au trône de la grâce."),
      d(6, "Jacques 4:6", "Jacques", 4, 6,
        "Il accorde une grâce plus excellente. C'est pourquoi l'Écriture dit : Dieu résiste aux orgueilleux, mais il fait grâce aux humbles.",
        "L'humilité est le canal de la grâce. L'orgueil le bloque. Vérifie où tu es positionné.",
        "Père, humilie mon cœur. Donne-moi grâce sur grâce.",
        "Je décrète que je marche dans l'humilité pour recevoir Ta grâce."),
      d(7, "Jean 1:16", "Jean", 1, 16,
        "Nous avons tous reçu de sa plénitude, et grâce pour grâce.",
        "« Grâce pour grâce » : une vague de grâce remplace l'autre. Le flux est continu, jamais épuisé.",
        "Jésus, je reçois grâce pour grâce de Ta plénitude.",
        "Je décrète que je suis comblé(e) d'une grâce qui se renouvelle sans cesse."),
    ],
  },
];

export function getThemedPlan(id: string): ThemedPlan | undefined {
  return THEMED_PLANS.find((p) => p.id === id);
}
